// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'amplify_core', 'amplify_store'], function($, _, Backbone, amplify) {
    var BaseView;
    return BaseView = Backbone.View.extend({
      Amplify: amplify,
      logger: function(msg) {
        return this.Amplify.publish('log', msg);
      }
    });
  });

}).call(this);
