// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var BaseCollection;
    return BaseCollection = Backbone.Collection.extend({
      Amplify: amplify,
      logger: function(msg) {
        return this.Amplify.publish('log', msg);
      }
    });
  });

}).call(this);
