// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'mustache'], function($, _, Backbone, Mustache) {
    var BaseView;
    return BaseView = Backbone.View.extend({
      extend: function(obj, mixin) {
        var method, name, _results;
        _results = [];
        for (name in mixin) {
          method = mixin[name];
          _results.push(obj[name] = method);
        }
        return _results;
      },
      include: function(klass, mixin) {
        return this.extend(klass.prototype, mixin);
      },
      Amplify: amplify,
      Mustache: Mustache,
      logger: function(msg) {
        return this.Amplify.publish('log', msg);
      }
    });
  });

}).call(this);
