// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'amplify_core', 'amplify_store'], function($, _, Backbone, amplify) {
    var BaseModel;
    return BaseModel = Backbone.Model.extend({
      Amplify: amplify,
      logger: function(msg) {
        return this.Amplify.publish('log', msg);
      },
      initialize: function() {
        this.logger(this.id);
        return this.logger(this.cid);
      }
    });
  });

}).call(this);
