// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'underscore', 'backbone', 'amplify'], function($, _, Backbone, amplify) {
    var BaseRouter;
    return BaseRouter = Backbone.Router.extend({
      Amplify: amplify,
      logger: function(msg) {
        return this.Amplify.publish('log', msg);
      }
    });
  });

}).call(this);
