// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'amplify', 'backbone'], function($, _, amplify, Backbone) {
    var CrippledClientSync, originalSync;
    originalSync = Backbone.sync;
    CrippledClientSync = function(method, model, options) {
      var methodMap, type;
      methodMap = {
        'create': 'POST',
        'update': 'PUT',
        'delete': 'DELETE',
        'read': 'GET'
      };
      type = methodMap[method];
      options = _.extend(options, {
        dataType: 'xml',
        contentType: 'application/xml',
        processData: false
      });
      if (model.get('digest') != null) {
        options.basic_auth_digest = model.get('digest');
      }
      options.beforeSend = function(xhr) {
        xhr.setRequestHeader('X-Crippled-Client', 'yes');
        xhr.setRequestHeader('X-Method', type);
        xhr.setRequestHeader('X-Rest-Method', type);
        xhr.setRequestHeader('X-Requested-With', 'XMLHTTPRequest');
        if (options.basic_auth_digest) {
          xhr.setRequestHeader('X-Authorization', "Basic " + options.basic_auth_digest);
          return xhr.setRequestHeader('Authorization', "Basic " + options.basic_auth_digest);
        }
      };
      return originalSync.apply(Backbone, [method, model, options]);
    };
    return CrippledClientSync;
  });

}).call(this);
