// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'base64'], function($, _, Base64) {
    var Helpers;
    Helpers = {
      id_safe: function(string) {
        var out, reg;
        reg = new RegExp('/\s*\W/gi');
        out = string.replace(/\s*\W/gi, '_');
        if (out === 'undefined' || out === void 0) {
          return null;
        }
        return out;
      }
    };
    return Helpers;
  });

}).call(this);
