// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'amplify'], function($, _, amplify) {
    var LocalStorageSync;
    LocalStorageSync = function(method, model, options) {
      var resp, store;
      store = model.localStorage || model.collection.localStorage;
      switch (method) {
        case "read":
          if (model.id) {
            resp = store.find(model);
          } else {
            resp = store.findAll();
          }
          break;
        case "create":
          resp = store.create(model);
          break;
        case "update":
          resp = store.update(model);
          break;
        case "delete":
          resp = store.destroy(model);
      }
      if (resp) {
        return options.success(resp);
      } else {
        return options.error("Record not fonund");
      }
    };
    return LocalStorageSync;
  });

}).call(this);
