// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'amplify'], function($, _, amplify) {
    var Messenger;
    return Messenger = (function() {

      function Messenger(view, id) {
        this.view = view;
        this.id = id;
        if (this.view.$el != null) {
          this.flash_container = this.view.$el.find("#flash-message-" + this.id);
        } else {
          this.flash_container = this.view.find("#flash-message-" + this.id);
        }
        this.register(this.id);
      }

      Messenger.prototype.register = function(id) {
        var _this = this;
        amplify.subscribe(id, function(type, msg) {
          if (type != null) {
            _this.flash_container.addClass(type);
          }
          if (msg != null) {
            msg += ' <i class="icon-remove-sign"></i>';
            return _this.flash_container.html(msg).fadeIn('fast');
          }
        });
        return this.flash_container.on('click', 'i', function(e) {
          e.preventDefault();
          return _this.flash_container.fadeOut('fast');
        });
      };

      return Messenger;

    })();
  });

}).call(this);
