// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore'], function($, _) {
    var Messenger;
    return Messenger = (function() {

      function Messenger(view, id, DELAY) {
        var _ref;
        this.view = view;
        this.id = id;
        this.DELAY = DELAY;
        this.DELAY = (_ref = this.DELAY) != null ? _ref : 5000;
        if (this.view.$el != null) {
          this.flash_container = this.view.$el.find("#flash-message-" + this.id);
        } else {
          this.flash_container = this.view.find("#flash-message-" + this.id);
        }
        this.register(this.id);
      }

      Messenger.prototype.register = function(id) {
        var _this = this;
        amplify.subscribe(id, function(type, msg) {
          if (type != null) {
            _this.flash_container.addClass(type);
          }
          if (msg != null) {
            msg += ' <i class="icon-remove-sign"></i>';
            _this.flash_container.html(msg).fadeIn('fast');
            if (_this.DELAY != null) {
              return _.delay(function() {
                return _this.flash_container.html(msg).fadeOut('slow');
              }, _this.DELAY);
            }
          }
        });
        return this.flash_container.on('click', 'i', function(e) {
          e.preventDefault();
          return _this.flash_container.fadeOut('fast');
        });
      };

      return Messenger;

    })();
  });

}).call(this);
