// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'amplify_core', 'WorkspaceRouter'], function($, amplify, WorkspaceRouter) {
    amplify.subscribe('log', function(msg) {
      return console.log("LOG: " + msg);
    });
    return {
      init: function() {
        var router;
        return router = new WorkspaceRouter();
      }
    };
  });

}).call(this);
