// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'amplify_core', 'WorkspaceController', 'WorkspaceRouter', 'BaseModel'], function($, amplify, WorkspaceController, WorkspaceRouter, BaseModel) {
    var Workspace, model;
    amplify.subscribe('log', function(msg) {
      return console.log("LOG: " + msg);
    });
    model = new BaseModel();
    Workspace = {
      Controller: WorkspaceController,
      Router: new WorkspaceRouter()
    };
    return {
      init: function() {
        model.switch_sync('xmlSync');
        model.parse = model.xmlParse;
        model.id = 'tim@arc90.com';
        model.url = 'mocks/user_tim_c.xml';
        model.fetch();
        console.log(model);
        return console.log(model.attributes);
      }
    };
  });

}).call(this);
