// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'amplify', 'WorkspaceController', 'WorkspaceRouter', 'UserModel'], function($, amplify, WorkspaceController, WorkspaceRouter, UserModel) {
    var Workspace, ics360;
    amplify.subscribe('log', function(msg) {
      return console.log("LOG: " + msg);
    });
    ics360 = {
      services: {
        ixdirectory: './ixdirectory/api/rest/v2/',
        pxcentral: './pxcentral/api/rest/v1/',
        ixlibrary: './ixlibrary/api/sdo/rest/v1/',
        ixdoc: './ixdoc/api/rest/v2/'
      }
    };
    Workspace = {
      Controller: WorkspaceController,
      Router: new WorkspaceRouter()
    };
    return {
      init: function() {
        return $(function() {
          return Workspace.Controller.build_login();
        });
      }
    };
  });

}).call(this);
