// Generated by CoffeeScript 1.3.3
(function() {

  define(['cs!controller', 'cs!view', 'regular'], function(controller, view, regular) {
    controller.attach(view);
    return console.log('regular name is: ' + regular.name);
  });

}).call(this);
