// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'amplify_core', 'amplify_store'], function($, _, Backbone, amplify) {
    var WorkspaceController;
    WorkspaceController = {
      Amplify: amplify,
      workspace_button: $('#button-workspace'),
      workspace_breadcrumb: $('#breadcrump'),
      workspace_admin: $('#header-admin'),
      logger: function(msg) {
        return this.Amplify.publish('log', msg);
      }
    };
    _.extend(WorkspaceController, Backbone.Events);
    WorkspaceController.on("log", function(msg) {
      return this.logger(msg);
    });
    return WorkspaceController;
  });

}).call(this);
