// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel', 'base64'], function(BaseModel, Base64) {
    var WorkspaceStateModel;
    WorkspaceStateModel = BaseModel.extend({
      initialize: function() {
        return this.use_localStorage();
      }
    });
    return WorkspaceStateModel;
  });

}).call(this);
