// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView'], function(BaseView) {
    var WorkspaceView;
    return WorkspaceView = BaseView.extend({
      initialize: function(options) {
        return this.logger('View is ready!');
      }
    });
  });

}).call(this);
