// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView'], function(BaseView) {
    var WorkspaceLoginView;
    return WorkspaceLoginView = BaseView.extend({
      initialize: function(options) {
        if (options.template != null) {
          return this.template = options.template;
        }
      },
      render: function() {
        return this.$el.html(this.template.html());
      }
    });
  });

}).call(this);
