// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'mustache', 'text!templates/tpl_module_loader.html'], function(BaseView, Mustache, tpl_module_loader) {
    var WorkspaceCanvasView;
    return WorkspaceCanvasView = BaseView.extend({
      $target: $('#target'),
      tagName: 'section',
      className: 'canvas',
      tab: null,
      initialize: function(options) {
        this.$tab_el = options.controller.$workspace_tabs;
        if (options.template != null) {
          this.template = options.template;
        }
        this.template_tab = options.template_tab != null ? options.template_tab : $('#tpl-workspace-tab').html();
        if (!(options.app != null)) {
          return this.Amplify.publish('flash', 'warning', 'There was a problem locating that workspace.');
        }
        this.app = options.app;
        this.el.id = this.app.app;
        this.options.controller.trigger('stack_add', this);
        return this.render();
      },
      render: function() {
        var _this = this;
        this.$el.html(Mustache.render(tpl_module_loader, {
          module_name: this.app.app_label
        }));
        require(["modules/" + this.options.module_type], function(Module) {
          _this.module = Module;
          return _this.module.init(_this, _this.app);
        });
        this.$el.hide();
        this.$target.append(this.$el);
        this.render_tab(this.template_tab);
        return this.options.controller.trigger('new_tab', this.app.app);
      },
      render_tab: function(template) {
        this.tab = $(Mustache.render(template, {
          tab_class: '',
          tab_url: this.el.id,
          tab_label: this.app.app_label
        }));
        return this.$tab_el.append(this.tab);
      },
      activate: function() {
        this.tab.addClass('selected');
        return this.$el.show();
      },
      deactivate: function() {
        this.tab.removeClass('selected');
        return this.$el.hide();
      },
      is_active: function() {
        return this.tab.hasClass('selected');
      },
      destroy: function() {
        if (this.$tab_el != null) {
          this.tab = null;
          delete this.tab;
          this.$tab_el.find("li a[href=" + this.app.app + "]").parent().remove();
          this.$tab_el = null;
        }
        this.$el.html('');
        return this.options.controller.trigger('stack_remove', this);
      },
      remove_loader: function() {
        var _this = this;
        console.log(this);
        return this.$el.find('#module-loader').fadeOut('fast', function() {
          return _this.module.render();
        });
      }
    });
  });

}).call(this);
