// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'WorkspaceCanvasView'], function(BaseView, WorkspaceCanvasView) {
    var WorkspaceLoginView;
    return WorkspaceLoginView = BaseView.extend({
      events: {
        "submit form": "get_credentials"
      },
      initialize: function(options) {
        this.include(WorkspaceLoginView, WorkspaceCanvasView);
        if (options.template != null) {
          this.template = options.template;
        }
        if (options.template_tab != null) {
          return this.render_tab(options.template_tab);
        }
      },
      render: function() {
        return this.$el.html(this.template.html());
      },
      get_credentials: function(event) {
        var password, username;
        event.preventDefault();
        username = this.$el.find('input:text').val();
        password = this.$el.find('input:password').val();
        return this.options.controller.check_credentials(username, password);
      }
    });
  });

}).call(this);
