// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView'], function(BaseView) {
    var WorkspaceNavView;
    return WorkspaceNavView = BaseView.extend({
      events: {
        "click li a": "toggle_main_nav"
      },
      initialize: function(options) {
        return this.$sub_el = $(options.sub_el);
      },
      render: function() {
        this.$el.prepend(this.options.main_nav);
        this.$sub_el.html(this.options.sub_nav);
        return this.$sub_el.css({
          'min-height': this.$el.height()
        });
      },
      toggle_main_nav: function(e) {
        var $a, $li;
        e.preventDefault();
        $a = $(e.target).parent();
        $li = $a.parent();
        $li.addClass('open');
        $li.siblings().removeClass('open');
        this.$sub_el.find("#" + ($a.data('pc'))).removeClass();
        return this.$sub_el.find("#" + ($a.data('pc'))).siblings().addClass('sub_nav_off');
      }
    });
  });

}).call(this);
