// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'Messenger', 'text!templates/tpl_login.html'], function(BaseView, Messenger, tpl_login) {
    var WorkspaceLoginView;
    return WorkspaceLoginView = BaseView.extend({
      el: '#target',
      tab: null,
      events: {
        "submit #form-login form": "get_credentials"
      },
      render: function() {
        var html;
        html = this.Mustache.render($('#tpl-flash-message').html(), {
          cid: this.cid
        });
        html += this.Mustache.render(tpl_login, {
          cid: this.cid
        });
        this.$el.html(html);
        return this.messenger = new Messenger(this, this.cid);
      },
      destroy: function() {
        this.$el.find('#form-login').remove();
        return this.off();
      },
      get_credentials: function(event) {
        var password, username;
        event.preventDefault();
        username = this.$el.find('input:text').val();
        password = this.$el.find('input:password').val();
        return this.options.controller.check_credentials(username, password);
      }
    });
  });

}).call(this);
