// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var XMLSync, originalSync;
    originalSync = Backbone.sync;
    return XMLSync = function(method, model, options) {
      options = _.extend(options, {
        dataType: 'xml',
        contentType: 'application/xml',
        processData: false
      });
      return originalSync.apply(Backbone, [method, model, options]);
    };
  });

}).call(this);
