// Generated by CoffeeScript 1.4.0
(function() {

  define(['jquery', 'underscore', 'backbone'], function($, _, Backbone) {
    var XMLSync, originalSync;
    originalSync = Backbone.sync;
    return XMLSync = function(method, model, options) {
      var sync_options;
      sync_options = {
        dataType: 'xml',
        contentType: 'application/xml',
        processData: false,
        withCredentials: true
      };
      if (model.get('digest') !== void 0 || model.get('digest') !== null) {
        sync_options.headers = {
          'Authorization': "Basic " + (model.get('digest'))
        };
      }
      options = _.extend(options, sync_options);
      return originalSync.apply(Backbone, [method, model, options]);
    };
  });

}).call(this);
