// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'mustache', 'modules/PolicyView', 'amplify_core', 'amplify_store'], function($, _, Backbone, Mustache, PolicyView, amplify) {
    var PolicyModule;
    return PolicyModule = (function() {

      function PolicyModule(view, app, params) {
        this.view = view;
        this.app = app;
        this.params = params;
        this.load();
      }

      PolicyModule.prototype.load = function() {
        var _this = this;
        return this.callback_delay(500, function() {
          return _this.view.remove_loader();
        });
      };

      PolicyModule.prototype.render = function() {
        this.policy_view = new PolicyView({
          view: this.view,
          module: this
        });
        return this.policy_view.render();
      };

      PolicyModule.prototype.callback_delay = function(ms, func) {
        return setTimeout(func, ms);
      };

      return PolicyModule;

    })();
  });

}).call(this);
