// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'mustache', 'modules/PolicyView', 'modules/PolicyModel', 'amplify'], function($, _, Backbone, Mustache, PolicyView, PolicyModel, amplify) {
    var PolicyModule;
    return PolicyModule = (function() {

      function PolicyModule(view, app, params) {
        this.view = view;
        this.app = app;
        this.params = params;
        if (this.app.params != null) {
          this.params = this.app.params;
        }
        this.load();
      }

      PolicyModule.prototype.load = function() {
        var id,
          _this = this;
        if (this.params.id != null) {
          id = this.params.id;
        }
        if (this.params.url != null) {
          if (id == null) {
            id = this.params.url;
          }
        }
        console.log(this.view.options.controller.user);
        this.policy_model = new PolicyModel({
          id: id,
          urlRoot: this.view.options.controller.services.pxcentral,
          digest: this.view.options.controller.user.get('digest')
        });
        this.policy_view = new PolicyView({
          view: this.view,
          module: this,
          model: this.policy_model
        });
        return this.policy_model.fetch({
          headers: {
            'X-Authorization': "Basic " + (this.view.options.controller.user.get('digest')),
            'Authorization': "Basic " + (this.view.options.controller.user.get('digest'))
          },
          success: function(model, resp) {
            model.response_state();
            switch (model.get('fetch_state').code) {
              case "200":
                model.get_pxServerIndex();
                return _this.render();
              default:
                return amplify.publish('controller', 'warning', "Sorry, that policy could not be retrieved. " + (model.get('fetch_state').text));
            }
          },
          error: function(model, resp) {
            return amplify.publish('controller', 'warning', "Sorry, that policy could not be retrieved. " + resp);
          }
        });
      };

      PolicyModule.prototype.render = function() {
        this.view.remove_loader();
        return this.policy_view.render();
      };

      PolicyModule.prototype.callback_delay = function(ms, func) {
        return setTimeout(func, ms);
      };

      return PolicyModule;

    })();
  });

}).call(this);
