// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel', 'base64'], function(BaseModel, Base64) {
    var PolicyModel;
    PolicyModel = BaseModel.extend({
      initialize: function() {
        return this.use_cripple();
      },
      url: function() {
        return this.get('urlRoot') + 'policies/' + this.id;
      },
      get_pxServerIndex: function() {
        var doc;
        doc = this.get('document');
        return this.set('pxServerIndex', doc.find('Identifiers Identifier[name=pxServerIndex]').attr('value'));
      }
    });
    return PolicyModel;
  });

}).call(this);
