// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel', 'base64'], function(BaseModel, Base64) {
    var PolicyModel;
    PolicyModel = BaseModel.extend({
      initialize: function() {
        this.use_cripple();
        this.urlRoot = this.get('urlRoot');
        if (this.get('username')) {
          this.id = this.get('username');
        }
        if (this.get('username') && this.get('password')) {
          this.set({
            'digest': Base64.encode("" + (this.get('username')) + ":" + (this.get('password')))
          });
          return delete this.attributes.password;
        }
      },
      parse_identity: function() {
        var doc;
        doc = this.get('document');
        if (doc != null) {
          this.set('passwordHash', doc.find('Identity').attr('passwordHash'));
          this.set('name', doc.find('Identity Name').text());
          return this.set('email', doc.find('Identity Email').text());
        }
      }
    });
    return UserModel;
  });

}).call(this);
