// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseCollection', 'modules/SearchPolicyModel', 'modules/SearchPolicyView', 'base64'], function(BaseCollection, SearchPolicyModel, SearchPolicyView, Base64) {
    var SearchPolicyCollection;
    SearchPolicyCollection = BaseCollection.extend({
      model: SearchPolicyModel,
      views: [],
      parse: function(response) {
        return response.policies;
      },
      render: function() {
        var view, _i, _len, _ref;
        if (this.views.length > 0) {
          _ref = this.views;
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            view = _ref[_i];
            view.destroy();
            this.views.shift();
          }
          return this.populate();
        } else {
          return this.populate();
        }
      },
      populate: function() {
        var _this = this;
        return this.each(function(model) {
          return _this.views.push(new SearchPolicyView({
            model: model,
            container: _this.container
          }));
        });
      }
    });
    return SearchPolicyCollection;
  });

}).call(this);
