// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseCollection', 'modules/SearchPolicyModel', 'modules/SearchPolicyView', 'base64'], function(BaseCollection, SearchPolicyModel, SearchPolicyView, Base64) {
    var SearchPolicyCollection;
    SearchPolicyCollection = BaseCollection.extend({
      model: SearchPolicyModel,
      views: [],
      parse: function(response) {
        return response.policies;
      },
      render: function() {
        this.container.$el.find('table.module-search tbody').html('');
        this.views = [];
        return this.populate();
      },
      populate: function() {
        var _this = this;
        return this.each(function(model) {
          return _this.views.push(new SearchPolicyView({
            model: model,
            container: _this.container
          }));
        });
      }
    });
    return SearchPolicyCollection;
  });

}).call(this);
