// Generated by CoffeeScript 1.3.3
(function() {

  define(['modules/SearchContextModel', 'modules/SearchContextView', 'base64', 'Store', 'LocalStorageSync', 'amplify', 'Helpers', 'json'], function(SearchContextModel, SearchContextView, Base64, Store, LocalStorageSync, Amplify, Helpers, JSON) {
    var SearchContextCollection;
    return SearchContextCollection = Backbone.Collection.extend({
      Amplify: Amplify,
      model: SearchContextModel,
      views: [],
      localStorage: new Store('ics_saved_searches'),
      sync: LocalStorageSync,
      rendered: false,
      initialize: function() {
        this.bind('add', this.add_one, this);
        return this.bind('reset', this.add_many, this);
      },
      add_one: function(model) {
        console.log('add one');
        return this.render(model);
      },
      add_many: function(collection) {
        var _this = this;
        return collection.each(function(model) {
          return _this.render(model);
        });
      },
      render: function(model, parent) {
        var data;
        this.parent = parent || $('.search-menu-context');
        data = model.attributes;
        if (_.isObject(data.params)) {
          data.params = Helpers.serialize(data.params);
        }
        return model.view = new SearchContextView({
          parent: this.parent,
          data: data
        });
      },
      populate: function(html) {
        var _this = this;
        return this.each(function(model) {
          return _this.render(model, html);
        });
      }
    });
  });

}).call(this);
