// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel', 'base64'], function(BaseModel, Base64) {
    var SearchPolicyModel;
    SearchPolicyModel = BaseModel.extend({
      initialize: function() {}
    });
    return SearchPolicyModel;
  });

}).call(this);
