// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'Messenger', 'modules/SearchPolicyCollection', 'text!templates/tpl_search_container.html'], function(BaseView, Messenger, SearchPolicyCollection, tpl_search_container) {
    var SearchView;
    return SearchView = BaseView.extend({
      events: {
        "submit .filters form": "search"
      },
      initialize: function(options) {
        this.el = options.view.el;
        this.$el = options.view.$el;
        this.controller = options.view.options.controller;
        this.policies = new SearchPolicyCollection();
        this.policies.url = this.controller.services.pxcentral + 'policies?modified-after=2012-01-01&modified-before=2012-07-01';
        return this.policies.container = this;
      },
      render: function() {
        var html;
        html = this.Mustache.render($('#tpl-flash-message').html(), {
          cid: this.cid
        });
        html += this.Mustache.render(tpl_search_container, {
          cid: this.cid
        });
        this.$el.html(html);
        return this.messenger = new Messenger(this.options.view, this.cid);
      },
      search: function(e) {
        var search_val,
          _this = this;
        e.preventDefault();
        search_val = this.$el.find('input[type=search]').val();
        return this.policies.fetch({
          headers: {
            'X-Authorization': "Basic " + (this.controller.user.get('digest')),
            'Authorization': "Basic " + (this.controller.user.get('digest'))
          },
          success: function(collection, resp) {
            return collection.render();
          },
          error: function(collection, resp) {
            console.log(resp);
            return _this.Amplify.publish(_this.cid, 'warning', "There was a problem with this request: " + resp.status + " - " + resp.statusText);
          }
        });
      }
    });
  });

}).call(this);
