// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'Messenger', 'text!templates/tpl_search_menu_views_row.html', 'Helpers'], function(BaseView, Messenger, tpl_search_menu_views_row, Helpers) {
    var SearchContextView;
    return SearchContextView = BaseView.extend({
      tagName: 'tr',
      events: {
        "click a": "launch_search"
      },
      initialize: function(options) {
        this.parent = options.parent;
        this.target = this.parent.find('table tbody');
        this.data = options.data;
        return this.render();
      },
      render: function() {
        this.$el.append(this.Mustache.render(tpl_search_menu_views_row, this.data));
        return this.target.append(this.$el);
      },
      launch_search: function(e) {
        var href, params;
        e.preventDefault();
        href = Helpers.unserialize($(e.currentTarget).attr('href'));
        params = {
          url: href.url,
          query: href.query
        };
        this.options.controller.launch_module('search', params);
        return this.options.controller.Router.append_module('search', params);
      }
    });
  });

}).call(this);
