// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'mustache', 'amplify_core', 'amplify_store'], function($, _, Backbone, Mustache, amplify) {
    var TestModule;
    return TestModule = (function() {

      function TestModule(view, app, params) {
        this.view = view;
        this.app = app;
        this.params = params;
        this.load();
      }

      TestModule.prototype.load = function() {
        var rnd,
          _this = this;
        rnd = Math.floor(Math.random() * (4 - 1 + 1)) + 1;
        return this.callback_delay(rnd * 1000, function() {
          return _this.view.remove_loader();
        });
      };

      TestModule.prototype.render = function() {
        var tpl,
          _this = this;
        tpl = "<p>{{label}} Module is rendered</p>\n<p><a href=\"#app\" class=\"open_search_app\" data-pc-module=\"SearchModule\" data-pc-policy=\"123456789\">Open another tab</a></p>\n<p><a href=\"#app\" class=\"open_search_app\" data-pc-module=\"SearchModule\" data-pc-policy=\"987654321\">Open another tab</a></p>\n<p><a href=\"#app\" class=\"open_search_app\" data-pc-module=\"SearchModule\" data-pc-policy=\"987651234\">Open another tab</a></p>";
        this.view.$el.html(Mustache.render(tpl, {
          label: this.app.app_label
        }));
        return $('.open_search_app').on('click', function(e) {
          var $e, app, data;
          e.preventDefault();
          $e = $(e.target);
          data = $e.data();
          app = {
            app: "policy_view_" + data.pcPolicy,
            app_label: "Policy view " + data.pcPolicy,
            params: data
          };
          return _this.view.launch_child_app(app);
        });
      };

      TestModule.prototype.callback_delay = function(ms, func) {
        return setTimeout(func, ms);
      };

      return TestModule;

    })();
  });

}).call(this);
