// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'mustache', 'amplify_core', 'amplify_store'], function($, _, Backbone, Mustache, amplify) {
    var TestModule;
    return TestModule = {
      init: function(el) {
        this.el = el;
        return this.render();
      },
      render: function() {
        return this.el.html('TEST MODULE BE RENDERED!');
      }
    };
  });

}).call(this);
