// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['modules/IPM/IPMActionView'], function(IPMActionView) {
    var ChangePaymentPlanAction;
    return ChangePaymentPlanAction = (function(_super) {

      __extends(ChangePaymentPlanAction, _super);

      function ChangePaymentPlanAction() {
        this.processView = __bind(this.processView, this);

        this.processViewData = __bind(this.processViewData, this);
        return ChangePaymentPlanAction.__super__.constructor.apply(this, arguments);
      }

      ChangePaymentPlanAction.prototype.initialize = function() {
        return ChangePaymentPlanAction.__super__.initialize.apply(this, arguments);
      };

      ChangePaymentPlanAction.prototype.ready = function() {
        ChangePaymentPlanAction.__super__.ready.apply(this, arguments);
        return this.fetchTemplates(this.MODULE.POLICY, 'change-payment-plan', this.processView);
      };

      ChangePaymentPlanAction.prototype.processViewData = function(vocabTerms, view) {
        return ChangePaymentPlanAction.__super__.processViewData.call(this, vocabTerms, view);
      };

      ChangePaymentPlanAction.prototype.processView = function(vocabTerms, view) {
        this.processViewData(vocabTerms, view);
        return this.trigger("loaded", this, this.postProcessView);
      };

      ChangePaymentPlanAction.prototype.submit = function(e) {
        var values, _ref, _ref1, _ref2, _ref3;
        ChangePaymentPlanAction.__super__.submit.call(this, e);
        values = {
          startDate: (_ref = this.MODULE.POLICY.get('lastInterval').StartDate) != null ? _ref : null,
          endDate: (_ref1 = this.MODULE.POLICY.get('lastInterval').EndDate) != null ? _ref1 : null,
          termEffectiveDate: (_ref2 = this.MODULE.POLICY.get('firstTerm').EffectiveDate) != null ? _ref2 : null,
          termExpirationDate: (_ref3 = this.MODULE.POLICY.get('firstTerm').ExpirationDate) != null ? _ref3 : null
        };
        this.VALUES.formValues = _.extend(this.VALUES.formValues, values);
        return this.ChangeSet.commitChange(this.ChangeSet.getPolicyChangeSet(this.VALUES), this.callbackSuccess, this.callbackError);
      };

      return ChangePaymentPlanAction;

    })(IPMActionView);
  });

}).call(this);
