// Generated by CoffeeScript 1.4.0
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['modules/IPM/IPMActionView', 'text!modules/IPM/templates/tpl_home_action.html'], function(IPMActionView, tpl_home_action) {
    var HomeAction;
    return HomeAction = (function(_super) {

      __extends(HomeAction, _super);

      function HomeAction() {
        return HomeAction.__super__.constructor.apply(this, arguments);
      }

      HomeAction.prototype.initialize = function() {
        HomeAction.__super__.initialize.apply(this, arguments);
        this.ACTION_NAME = "Home";
        return this.events = {
          "click .ipm-home-action-view a": "dispatch"
        };
      };

      HomeAction.prototype.ready = function() {
        HomeAction.__super__.ready.apply(this, arguments);
        return this.trigger("loaded", this);
      };

      HomeAction.prototype.dispatch = function(e) {
        var view;
        e.preventDefault();
        view = $(e.currentTarget).attr('href');
        return this.MODULE.VIEW.route(view);
      };

      HomeAction.prototype.render = function() {
        var actions, html;
        actions = this.MODULE.CONFIG.ACTIONS;
        html = this.MODULE.VIEW.Mustache.render(tpl_home_action, this.MODULE.CONFIG);
        return this.$el.html(html);
      };

      return HomeAction;

    })(IPMActionView);
  });

}).call(this);
