// Generated by CoffeeScript 1.3.3
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['modules/IPM/IPMActionView'], function(IPMActionView) {
    var InvoiceAction;
    return InvoiceAction = (function(_super) {

      __extends(InvoiceAction, _super);

      function InvoiceAction() {
        this.processView = __bind(this.processView, this);
        return InvoiceAction.__super__.constructor.apply(this, arguments);
      }

      InvoiceAction.prototype.initialize = function() {
        return InvoiceAction.__super__.initialize.apply(this, arguments);
      };

      InvoiceAction.prototype.ready = function() {
        InvoiceAction.__super__.ready.apply(this, arguments);
        return this.fetchTemplates(this.MODULE.POLICY, 'invoice', this.processView);
      };

      InvoiceAction.prototype.processView = function(vocabTerms, view) {
        this.processViewData(vocabTerms, view);
        return this.trigger("loaded", this, this.postProcessView);
      };

      InvoiceAction.prototype.submit = function(e) {
        var label_stamp, timestamp;
        InvoiceAction.__super__.submit.call(this, e);
        timestamp = this.Helpers.makeTimestamp();
        label_stamp = this.Helpers.formatDate();
        return this.ChangeSet.commitChange(this.ChangeSet.getPolicyChangeSet(this.VALUES), this.callbackSuccess, this.callbackError);
      };

      return InvoiceAction;

    })(IPMActionView);
  });

}).call(this);
