// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['modules/IPM/IPMActionView'], function(IPMActionView) {
    var MakePaymentAction;
    return MakePaymentAction = (function(_super) {

      __extends(MakePaymentAction, _super);

      function MakePaymentAction() {
        this.processView = __bind(this.processView, this);

        this.processViewData = __bind(this.processViewData, this);
        return MakePaymentAction.__super__.constructor.apply(this, arguments);
      }

      MakePaymentAction.prototype.initialize = function() {
        return MakePaymentAction.__super__.initialize.apply(this, arguments);
      };

      MakePaymentAction.prototype.ready = function() {
        MakePaymentAction.__super__.ready.apply(this, arguments);
        return this.fetchTemplates(this.MODULE.POLICY, 'make-payment', this.processView);
      };

      MakePaymentAction.prototype.processViewData = function(vocabTerms, view) {
        return MakePaymentAction.__super__.processViewData.call(this, vocabTerms, view);
      };

      MakePaymentAction.prototype.processView = function(vocabTerms, view) {
        this.processViewData(vocabTerms, view);
        return this.trigger("loaded", this, this.postProcessView);
      };

      MakePaymentAction.prototype.submit = function(e) {
        MakePaymentAction.__super__.submit.call(this, e);
        this.VALUES.formValues.positivePaymentAmount = Math.abs(this.VALUES.formValues.paymentAmount || 0);
        this.VALUES.formValues.paymentAmount = -1 * this.VALUES.formValues.positivePaymentAmount;
        return this.ChangeSet.commitChange(this.ChangeSet.getPolicyChangeSet(this.VALUES), this.callbackSuccess, this.callbackError);
      };

      return MakePaymentAction;

    })(IPMActionView);
  });

}).call(this);
