// Generated by CoffeeScript 1.4.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['modules/IPM/IPMActionView'], function(IPMActionView) {
    var ReverseDisbursementAction;
    return ReverseDisbursementAction = (function(_super) {

      __extends(ReverseDisbursementAction, _super);

      function ReverseDisbursementAction() {
        this.processView = __bind(this.processView, this);

        this.processViewData = __bind(this.processViewData, this);
        return ReverseDisbursementAction.__super__.constructor.apply(this, arguments);
      }

      ReverseDisbursementAction.prototype.initialize = function() {
        return ReverseDisbursementAction.__super__.initialize.apply(this, arguments);
      };

      ReverseDisbursementAction.prototype.ready = function() {
        ReverseDisbursementAction.__super__.ready.apply(this, arguments);
        return this.fetchTemplates(this.MODULE.POLICY, 'reverse-disbursement', this.processView);
      };

      ReverseDisbursementAction.prototype.processViewData = function(vocabTerms, view) {
        return ReverseDisbursementAction.__super__.processViewData.call(this, vocabTerms, view);
      };

      ReverseDisbursementAction.prototype.processView = function(vocabTerms, view) {
        this.processViewData(vocabTerms, view);
        this.FormValidation.validators = {
          'amount': 'money'
        };
        return this.trigger("loaded", this, this.postProcessView);
      };

      ReverseDisbursementAction.prototype.submit = function(e) {
        var _ref;
        ReverseDisbursementAction.__super__.submit.call(this, e);
        this.VALUES.formValues.amount = (_ref = this.Helpers.formatMoney(this.VALUES.formValues.amount)) != null ? _ref : null;
        return this.ChangeSet.commitChange(this.ChangeSet.getPolicyChangeSet(this.VALUES), this.callbackSuccess, this.callbackError);
      };

      return ReverseDisbursementAction;

    })(IPMActionView);
  });

}).call(this);
