// Generated by CoffeeScript 1.3.3
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(['BaseView', 'Messenger'], function(BaseView, Messenger) {
    var IPMActionView;
    return IPMActionView = (function(_super) {

      __extends(IPMActionView, _super);

      function IPMActionView() {
        return IPMActionView.__super__.constructor.apply(this, arguments);
      }

      IPMActionView.prototype.MODULE = {};

      IPMActionView.prototype.initialize = function(options) {
        this["super"] = IPMActionView.prototype;
        if (options.MODULE != null) {
          this.MODULE = options.MODULE;
        }
        if (this.MODULE.CONTAINER) {
          this.$el = this.MODULE.CONTAINER;
        }
        return delete this.options;
      };

      IPMActionView.prototype.render = function() {};

      IPMActionView.prototype.validate = function() {};

      IPMActionView.prototype.preview = function() {};

      return IPMActionView;

    })(BaseView);
  });

}).call(this);
