// Generated by CoffeeScript 1.3.3
(function() {

  define(['jquery', 'underscore', 'backbone', 'mustache', 'Messenger', 'loader'], function($, _, Backbone, Mustache, Messenger, CanvasLoader) {
    var IPMModule;
    return IPMModule = (function() {

      function IPMModule() {}

      IPMModule.prototype.Amplify = amplify;

      return IPMModule;

    })();
  });

}).call(this);
