// Generated by CoffeeScript 1.4.0
(function() {

  define(['BaseModel'], function(BaseModel) {
    var SearchContextModel;
    return SearchContextModel = BaseModel.extend({
      initialize: function() {
        return this.use_localStorage('ics_saved_searches');
      }
    });
  });

}).call(this);
