// Generated by CoffeeScript 1.4.0
(function() {

  define(['BaseModel'], function(BaseModel) {
    var SearchPolicyModel;
    SearchPolicyModel = BaseModel.extend({
      initialize: function() {}
    });
    return SearchPolicyModel;
  });

}).call(this);
