// Generated by CoffeeScript 1.4.0
(function() {

  define(['BaseCollection', 'modules/Search/SearchContextModel', 'modules/Search/SearchContextView', 'base64', 'Store', 'LocalStorageSync', 'Helpers', 'mustache', 'text!modules/Search/templates/tpl_search_menu_views.html'], function(BaseCollection, SearchContextModel, SearchContextView, Base64, Store, LocalStorageSync, Helpers, Mustache, tpl_search_menu_views) {
    var SearchContextCollection;
    return SearchContextCollection = BaseCollection.extend({
      model: SearchContextModel,
      activeView: null,
      menu: null,
      localStorage: new Store('ics_saved_searches'),
      sync: LocalStorageSync,
      rendered: false,
      initialize: function() {
        return this.menu = $(Mustache.render(tpl_search_menu_views, {}));
      },
      getMenu: function(view) {
        this.activeView = view;
        return this.menu;
      },
      closeMenu: function() {
        if (this.activeView != null) {
          this.activeView.clear_menus();
          return this.activeView.controls.removeClass('active');
        }
      },
      destroy: function(id) {
        var model;
        model = this.get(id);
        if (model.destroy()) {
          return this.remove(model);
        }
      }
    });
  });

}).call(this);
