// Generated by CoffeeScript 1.4.0
(function() {

  define(['BaseModel', 'modules/Search/SearchContextView'], function(BaseModel, SearchContextView) {
    var SearchContextModel;
    return SearchContextModel = BaseModel.extend({
      initialize: function() {
        var data, view;
        this.use_localStorage('ics_saved_searches');
        data = this.attributes;
        if (_.isObject(data.params)) {
          data.params = this.Helpers.serialize(data.params);
        }
        return view = new SearchContextView({
          parent: this.collection.menu,
          data: data,
          controller: this.collection.controller,
          model: this
        });
      }
    });
  });

}).call(this);
