// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'text!modules/ReferralQueue/templates/tpl_referral_task_row.html'], function(BaseView, tpl_row) {
    var ReferralTaskView;
    return ReferralTaskView = BaseView.extend({
      tagName: 'tr',
      events: {
        "click": "openPolicy"
      },
      initialize: function(options) {
        this.PARENT_VIEW = options.parent_view || {};
        return this;
      },
      render: function() {
        var html;
        html = this.Mustache.render(tpl_row, this.model.getViewData());
        return this.$el.append(html);
      },
      openPolicy: function(e) {
        var $el, params;
        e.preventDefault();
        $el = $(e.currentTarget);
        params = {
          url: this.model.get('relatedQuoteId')
        };
        this.PARENT_VIEW.MODULE.view.options.controller.launch_module('policyview', params);
        return this.PARENT_VIEW.MODULE.view.options.controller.Router.append_module('policyview', params);
      }
    });
  });

}).call(this);
