// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'text!modules/ReferralQueue/templates/tpl_referral_task_row.html'], function(BaseView, tpl_row) {
    var ReferralTaskView;
    return ReferralTaskView = BaseView.extend({
      tagName: 'tr',
      initialize: function(options) {
        this.PARENT_VIEW = options.parent_view || {};
        return this;
      },
      render: function() {
        var html;
        html = this.Mustache.render(tpl_row, this.model.getViewData());
        return this.$el.append(html);
      }
    });
  });

}).call(this);
