// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel', 'moment'], function(BaseModel, moment) {
    var ReferralTaskModel;
    return ReferralTaskModel = BaseModel.extend({
      initialize: function() {},
      getAssignedTo: function() {
        switch (this.get('AssignedTo')) {
          case "Underwriting":
            return "Underwriter";
          case "Agent":
            return this.getOwningAgent();
          default:
            return "";
        }
      },
      getOwningAgent: function() {
        var item;
        if (this.get('DataItem') != null) {
          item = _.find(this.get('DataItem'), function(item) {
            return _.has(item, 'name') && item.name === 'OwningAgent';
          });
          return item.value;
        } else {
          return '';
        }
      },
      getViewData: function() {
        var attributes;
        attributes = _.pick(this.attributes, 'relatedQuoteId', 'insuredLastName', 'status', 'Type', 'lastUpdated', 'SubmittedBy');
        moment.calendar = {
          lastDay: '[Yesterday at] LT',
          sameDay: '[Today at] LT',
          nextDay: '[Tomorrow at] LT',
          lastWeek: '[last] dddd [at] LT',
          nextWeek: 'dddd [at] LT',
          sameElse: 'LLL'
        };
        attributes.lastUpdated = moment(attributes.lastUpdated).calendar();
        attributes.assignedTo = this.getAssignedTo();
        return attributes;
      }
    });
  });

}).call(this);
