// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel'], function(BaseModel) {
    var ReferralTaskModel;
    return ReferralTaskModel = BaseModel.extend({
      initialize: function() {}
    });
  });

}).call(this);
