// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView'], function(BaseView) {
    var ReferralTaskView;
    return ReferralTaskView = BaseView.extend({
      tagName: 'tr',
      initialize: function(options) {
        return this.PARENT_VIEW = options.parent_view || {};
      }
    });
  });

}).call(this);
