// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'Messenger', 'text!modules/ZenDesk/templates/tpl_zendesk_container.html'], function(BaseView, Messenger, tpl_zd_container) {
    var ZenDeskView;
    return ZenDeskView = BaseView.extend({
      initialize: function(options) {
        var _ref;
        _ref = [options.$el, options.policy, options.policy_view], this.$el = _ref[0], this.policy = _ref[1], this.policy_view = _ref[2];
        return this;
      },
      fetch: function() {
        return this.fetch_tickets(this.policy.get_policy_id());
      },
      render: function() {
        this.$el.html(this.Mustache.render(tpl_zd_container, {
          results: this.tickets.results
        }));
        return this.show();
      },
      show: function() {
        return this.$el.fadeIn('fast');
      },
      hide: function() {
        return this.$el.hide();
      },
      fetch_tickets: function(query) {
        var _this = this;
        if (_.isEmpty(query)) {
          this.Amplify.publish(this.policy_view.cid, 'warning', "This policy is unable to search the ZenDesk API at this time. Sorry.");
          return false;
        } else {
          $.ajax({
            url: this.policy_view.services.zendesk,
            type: 'GET',
            contentType: 'application/json',
            data: {
              query: query,
              sort_order: 'desc',
              sort_by: 'created_at'
            },
            dataType: 'json',
            success: function(data, textStatus, jqXHR) {
              _this.tickets = data;
              return _this.render();
            },
            error: function(jqXHR, textStatus, errorThrown) {
              _this.Amplify.publish(_this.policy_view.cid, 'warning', "This policy is unable to access the ZenDesk API at this time. Message: " + textStatus);
              return false;
            }
          });
        }
        return this;
      }
    });
  });

}).call(this);
