// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseView', 'Messenger', 'text!templates/tpl_zendesk_container.html'], function(BaseView, Messenger, tpl_zd_container) {
    var ZenDeskView;
    return ZenDeskView = BaseView.extend({
      events: {
        'click a[href=assigned_to]': function(e) {
          return this.process_event(e);
        }
      },
      initialize: function(options) {
        var _ref;
        return _ref = [options.$el, options.policy, options.policy_view], this.$el = _ref[0], this.policy = _ref[1], this.policy_view = _ref[2], _ref;
      },
      render: function() {
        var tickets;
        tickets = this.fetch_tickets(this.policy.get_policy_id());
        this.$el.html(this.Mustache.render(tpl_zd_container, {
          results: tickets.results
        }));
        return this.show();
      },
      show: function() {
        return this.$el.fadeIn('fast');
      },
      hide: function() {
        return this.$el.hide();
      },
      process_event: function(e) {
        e.preventDefault();
        return $(e.currentTarget);
      },
      fetch_tickets: function(query) {
        var digest,
          _this = this;
        if (_.isEmpty(query)) {
          this.Amplify.publish(this.policy_view.cid, 'warning', "This policy is unable to search the ZenDesk API at this time. Sorry.");
          false;
        }
        digest = this.Helpers.createDigest('darren.newton@arc90.com', 'arc90zen');
        if (!digest) {
          this.Amplify.publish(this.policy_view.cid, 'warning', "This policy is unable to search the ZenDesk API at this time. Sorry.");
          return false;
        } else {
          return $.ajax({
            url: "" + this.policy_view.services.zendesk + "/search.json",
            type: 'GET',
            contentType: 'application/json',
            data: {
              query: query,
              sort_order: 'desc',
              sort_by: 'created_at'
            },
            dataType: 'json',
            beforeSend: function(xhr) {
              return xhr.setRequestHeader('Authorization', "Basic " + digest);
            },
            headers: {
              'Authorization': "Basic " + digest
            },
            username: 'darren.newton@arc90.com',
            password: 'arc90zen',
            success: function(data, textStatus, jqXHR) {
              console.log(data);
              return data;
            },
            error: function(jqXHR, textStatus, errorThrown) {
              _this.Amplify.publish(_this.policy_view.cid, 'warning', "This policy is unable to access the ZenDesk API at this time. Message: " + textStatus);
              console.log(jqXHR);
              return false;
            }
          });
        }
      }
    });
  });

}).call(this);
