// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel'], function(BaseModel) {
    var SearchContextModel;
    SearchContextModel = BaseModel.extend({
      initialize: function() {
        return this.use_localStorage('ics_saved_searches');
      }
    });
    return SearchContextModel;
  });

}).call(this);
