// Generated by CoffeeScript 1.3.3
(function() {

  define(['BaseModel'], function(BaseModel) {
    var RenewalUnderwritingModel;
    return RenewalUnderwritingModel = BaseModel.extend({
      initialize: function() {
        return this.use_backbone_auth();
      },
      url: function() {
        return "" + (this.get('urlRoot')) + "policies/" + this.id + "/underwriting";
      }
    });
  });

}).call(this);
