// Generated by CoffeeScript 1.4.0
(function() {

  define(['BaseModel'], function(BaseModel) {
    var RenewalUnderwritingModel;
    return RenewalUnderwritingModel = BaseModel.extend({
      initialize: function() {
        return this.use_backbone_auth();
      },
      url: function() {
        return "" + (this.get('urlRoot')) + "policies/" + this.id + "/renewalunderwriting";
      },
      putFragment: function(success, error, fragment) {
        if (success == null) {
          success = this.putSuccess;
        }
        if (error == null) {
          error = this.putError;
        }
        return this.save({}, {
          data: JSON.stringify(fragment),
          contentType: 'application/json',
          success: success,
          error: error
        });
      }
    });
  });

}).call(this);
